export const constants = {
  ENVIRONMENT_VARIABLES: {
    DATABASE_HOST: 'DATABASE_HOST',
    DATABASE_PORT: 'DATABASE_PORT',
    DATABASE_USENAME: 'DATABASE_USERNAME',
    DATEBASE_PASSWORD: 'DATEBASE_PASSWORD',
    DATABASE_NAME: 'DATABASE_NAME',
    NODE_ENV: 'NODE_ENV',
    APP_PORT: 'APP_PORT',
    APP_VERSION: 'APP_VERSION',
    ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
    PASSWORD_ENCRYPTION_SALT: 'PASSWORD_ENCRYPTION_SALT',
  },
  REPOSITORY: {
    USER_REPOSITORY: 'USER_REPOSITORY',
    PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
    ORGANIZATION_REPOSITORY: 'ORGANIZATION_REPOSITORY',
    ORDER_REPOSITORY: 'ORDER_REPOSITORY',
    PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
    ROLE_REPOSITORY: 'ROLE_REPOSITORY',
    ROLE_PERMISSION_REPOSITORY: 'ROLE_PERMISSION_REPOSITORY',
    ORDER_PRODUCTS_PERMISSION_REPOSITORY:
      'ORDER_PRODUCTS_PERMISSION_REPOSITORY',
  },
  DATA_SOURCE: 'DATA_SOURCE',
  SWAGGER: {
    TITLE: 'Permissions Business Service',
    DESCRIPTION:
      'Service built to spin up permissions based management systems',
    VERSION: '1.0',
    PATH: 'swagger',
  },
  APP: {
    RUNNING_PORT: 'App running on port - ',
  },
  SYSTEM_ADMIN: {
    ORGANIZATION_NAME: 'BASE_SYSTEM',
  },
};
